source 'http://ruby.taobao.org'
#ruby '2.0.0'
gem 'rails', '~> 4.0.0'
gem 'mysql2', '0.3.13'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass', '>= 3.0.0.0'
gem 'bootstrap-will_paginate'
gem 'font-awesome-rails'
gem 'cancan'
gem 'devise'
gem 'figaro'
gem 'rolify'
gem 'simple_form'

#blow only render on linux
#gem 'therubyracer', :platform=>:ruby
#gem 'mechanize'
#gem 'hpricot'
