base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: true
  wait_timeout: 600
  pool: 25
  username: root
  password: kenrome001
  host: localhost
  port: 3306

development:
  <<: *base
  database: hot_list

test:
  <<: *base
  database: hot_list

production:
  <<: *base
  database: hot_list
